### ISSUE TITLE
Exception when start the application

### ISSUE THREAD

**Issue by fran46** [Maxx53/SCMBot#331]
Hi!
SCMBot has always worked well for me. I have made many purchases with the program :)

The problem is that what started yesterday and gave me the following error:
![scmbot_error](https://cloud.githubusercontent.com/assets/12441934/7628267/90ffa07c-fa21-11e4-9169-e5e3ae4ccb77.png)

---- Details error ----

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at SCMBot.Main.LoadSettings(Boolean loadtabs)
   at SCMBot.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)

**Comment by Maxx53** [comment]
Well, use search.
https://github.com/Maxx53/SCMBot/issues/208

**Comment by fran46** [comment]
Thank you very much. Problem solved by deleting the file Settings.xml
